export const WELCOME_SUCCESS = "WECLOME_SUCCESS";
export const WELCOME_ERROR = "WELCOME_ERROR";
export const QUESTIONS_SUCCESS = "QUESTIONS_SUCCESS";
export const QUESTIONS_ERROR = "QUESTIONS_ERROR";

